### ISSUE TITLE
任务认领 - 版本 2.1.alpha

### ISSUE THREAD

**Issue by fy0** [fy0/godot-doc-cn#1]

**Comment by fy0** [comment]
认领 @GDScript - 已完成
认领 AcceptDialog - 已完成
认领 page/tutorials/step_by_step/resources.rst 后半部分 - 已完成

**Comment by vipsbpig** [comment]
认领 @Global Scope

**Comment by vipsbpig** [comment]
认领 Global Scope AABB

**Comment by zaevi** [comment]
认领 ConfigFile

**Comment by Oberon-Zheng** [comment]
认领 ：
     - 基本教程
     - 物理
     - 数学
     - 可能会带上其他的部分（具体什么部分完全看心情）

**Comment by wangshuo1617** [comment]
认领 ../page/tutorials/engine/viewports.rst 全篇 **已完成**
认领 ../page/tutorials/engine/multiple_resolutions.rst 全篇 **已完成**
认领 ../page/tutorials/engine/inputevent.rst 全篇 **已完成**
认领 ../page/tutorials/engine/mouse_and_input_coordinates.rst 全篇 **已完成**
认领 ../page/tutorials/engine/project_organization.rst 全篇

**Comment by zhangshiqian1214** [comment]
认领 ../page/tutorials/engine/data_paths.rst 全篇 已完成

**Comment by zhangshiqian1214** [comment]
认领 ../page/tutorials/engine/project_organization.rst
认领 ../page/tutorials/engine/pausing_games.rst
认领 ../page/tutorials/engine/background_loading.rst

**Comment by l12g** [comment]
认领 ../page/tutorials/2d/canvas_layers.rst.rst 全篇 **已完成**
认领 ../page/tutorials/2d/custom_drawing_in_2d.rst 全篇 **已完成**
认领 ../page/tutorials/2d/viewport_and_canvas_transforms.rst 全篇 **已完成**
认领 ../page/tutorials/2d/size_and_anchors.rst 全篇 **已完成**
